import prompts from 'prompts';
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import * as path from 'path';

function generateWorkflow(appName: string): string {
  const templatePath = path.resolve(__dirname, '../../../../manifests/templates/plattr-deploy.yml');
  if (existsSync(templatePath)) {
    return readFileSync(templatePath, 'utf-8').replace(/__APP_NAME__/g, appName);
  }

  // Fallback: inline template
  return `# Generated by \`plattr init\` — DO NOT EDIT
# To update, run \`plattr upgrade\`
name: Plattr Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  APP_NAME: ${appName}
  AWS_REGION: ca-central-1

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: \${{ steps.build.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: test --source=.
      - name: Build and push
        id: build
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: >-
            build-and-push
            --source=.
            --app-name=${appName}
            --environment=ci
            --registry-url=\${{ env.ECR_REGISTRY }}

  staging:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to staging
        run: echo "Deploying to staging"

  production:
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy to production
        run: echo "Deploying to production"
`;
}

export async function initCommand() {
  if (existsSync('plattr.yaml')) {
    console.log('plattr.yaml already exists. Delete it first to re-initialize.');
    process.exit(1);
  }

  // Auto-detect framework
  let detectedFramework = 'docker';
  if (existsSync('next.config.js') || existsSync('next.config.mjs') || existsSync('next.config.ts')) {
    detectedFramework = 'nextjs';
  } else if (existsSync('Gemfile') && existsSync('config.ru')) {
    detectedFramework = 'rails';
  } else if (!existsSync('Dockerfile') && existsSync('index.html')) {
    detectedFramework = 'static';
  }

  const answers = await prompts([
    {
      type: 'text',
      name: 'name',
      message: 'App name?',
      initial: path.basename(process.cwd()),
      validate: (v: string) =>
        /^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(v) || v.length === 1 && /^[a-z0-9]$/.test(v) || 'Must be lowercase alphanumeric with hyphens',
    },
    {
      type: 'select',
      name: 'framework',
      message: `Framework? (detected: ${detectedFramework})`,
      choices: [
        { title: 'Next.js', value: 'nextjs' },
        { title: 'Rails', value: 'rails' },
        { title: 'Static', value: 'static' },
        { title: 'Dockerfile', value: 'docker' },
      ],
      initial: ['nextjs', 'rails', 'static', 'docker'].indexOf(detectedFramework),
    },
    { type: 'confirm', name: 'database', message: 'Enable database?', initial: true },
    { type: 'confirm', name: 'storage', message: 'Enable storage?', initial: false },
    { type: 'confirm', name: 'auth', message: 'Enable authentication?', initial: false },
    { type: 'confirm', name: 'redis', message: 'Enable Redis cache?', initial: false },
    { type: 'confirm', name: 'search', message: 'Enable OpenSearch?', initial: false },
  ]);

  if (!answers.name) {
    console.log('Cancelled.');
    return;
  }

  // Generate plattr.yaml
  let yamlContent = `name: ${answers.name}\nframework: ${answers.framework}\n`;
  if (answers.database) {
    yamlContent += `\ndatabase:\n  enabled: true\n`;
  }
  if (answers.storage) {
    yamlContent += `\nstorage:\n  enabled: true\n  buckets:\n    - name: uploads\n      public: false\n`;
  }
  if (answers.auth) {
    yamlContent += `\nauth:\n  enabled: true\n  providers:\n    - google\n    - github\n`;
  }
  if (answers.redis) {
    yamlContent += `\nredis:\n  enabled: true\n`;
  }
  if (answers.search) {
    yamlContent += `\nsearch:\n  enabled: true\n`;
  }
  yamlContent += `\nlocal:\n  port: 3000\n`;

  writeFileSync('plattr.yaml', yamlContent);
  console.log('Created plattr.yaml');

  // Generate GitHub Actions workflow
  mkdirSync('.github/workflows', { recursive: true });
  const workflowContent = generateWorkflow(answers.name);
  writeFileSync('.github/workflows/plattr-deploy.yml', workflowContent);
  console.log('Created .github/workflows/plattr-deploy.yml');

  console.log(`\nNext steps:`);
  console.log(`  plattr dev     — start local development`);
  console.log(`  plattr test    — run tests with full infrastructure`);
  console.log(`  git push         — deploy to staging automatically`);
}
